
service: serverless-graphql

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  memorySize: 128

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: ANY
        cors: true

      # It's where you define your AWS Lambda Functions, the events that trigger 
      # them and any AWS infrastructure resources they require, all in a file called serverless. yml . 
      # To get started building your first Serverless Framework project, create a service .